### ISSUE TITLE
reporting-org documentation mentions non-existent @role 

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Schemas#32] opened 2013-10-23 13:22 UTC
@role is mentioned in the reporting-org documentation (https://github.com/IATI/IATI-Schemas/blob/master/iati-common.xsd#L86), but it does not have an attribute by this name.

**Comment by caprenter** [comment] 2014-01-21 16:06
Can you suggest some alternative text please @bill-anderson

**Comment by caprenter** [comment] 2014-01-21 16:08
Sorry, I see this is a duplicate of 
https://github.com/IATI/IATI-Schemas/pull/44
and that you have suggested a fix.

**Closed as completed by caprenter** 2014-01-21 16:08 UTC
